### ISSUE TITLE
Specification on Signature Algorithm is inconsistent

### ISSUE THREAD

**Issue by sintemal** [SAFE-eV/OCMF-Open-Charge-Metering-Format#28]
In the section on signature data, the Signature Algorithm (SA) has a cardinality of 1..1, but the description specifies it as optional. https://github.com/SAFE-eV/OCMF-Open-Charge-Metering-Format/blob/dabb0ebbc244eafce3535b95a8007e41ab89eab7/OCMF-en.md?plain=1#L395

Furthermore, it references to Table 21 instead of 22 for possible values, which is the table on Current Types. Additionaly the default value of the signature algorithm in Table 22 is only specified for OCMF version 0.4.

**Comment by mhei** [comment]
This issue can be closed since the proposed changes are already merged.
