### ISSUE TITLE
OCPP - OCMF Data set Integration

### ISSUE THREAD

**Issue by FlorianRieglerKeba** [SAFE-eV/OCMF-Open-Charge-Metering-Format#3]
Define how an OCMF data set has to be encoded when it is integrated in a StopTransaction.req.
Currently more methods are used e.g.:
a) alphanumeric
b) Hex

**Comment by simonschllng** [comment]
This is actual up to the transport protocol and should not be defined in OCMF. We should make a pull request there.

**Comment by FlorianRieglerKeba** [comment]
The encoding of the content in the StopTransation.req should be defined in OCPP.
