### ISSUE TITLE
Inconsistent Description in the Documentation for Loss Compensation

### ISSUE THREAD

**Issue by maba-evo** [SAFE-eV/OCMF-Open-Charge-Metering-Format#35]
It looks like there is something like a typo which makes it quite hard to implement the Loss Compensation. 
The example file defines the LC property as follows:
```
...
 "LC": {
        "LN": "cable_name",
        "LI": 1,
        "LR": 2,
        "LU": "mOhm"
    },
...
```
In table 24 the `LU` property is defined as a required number, but the textual description defines the property as a string with either one of the two values "mOhm" or "uOhm".

I guess that the textual description is correct, but I am not 100% sure.
And if my assumption is right does this property use the same values as defined in table 20 Units.

Thanks and kind regards.

**Comment by mhei** [comment]
Yes, I'm with you. Looks like a typo. I've created the referenced PR to fix it. It will be most probably discussed in the next OCMF UA meeting.
